FROM node:16-bullseye

RUN apt update
RUN apt -y install build-essential python3 python3-dev g++

ENV NODE_ENV=development

WORKDIR /home/node
COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

USER node
EXPOSE 8080
CMD ["npm", "run", "dev"]
