version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
      - ./tailwind.config.js:/home/node/tailwind.config.js
    command: npm run dev
    ports:
      - "8080:8080"
      - "1234:1234"
    environment:
      NODE_ENV: development
